# Artifact Hub repository metadata file
# https://artifacthub.io/docs/topics/repositories/

repositoryID: gobservability
name: Gobservability
displayName: Gobservability
url: https://thomascardin.github.io/gobservability/

owners:
  - name: Thomas Cardin
    email: thomas@example.com  # Change to your email

links:
  - name: GitHub
    url: https://github.com/ThomasCardin/gobservability
  - name: Documentation
    url: https://github.com/ThomasCardin/gobservability/blob/main/README.md
