repositoryID: gobservability
name: Gobservability
displayName: Gobservability
url: https://thomascardin.github.io/gobservability/

owners:
  - name: Thomas Cardin
    email: tomcardin@outlook.com

links:
  - name: GitHub
    url: https://github.com/ThomasCardin/gobservability
  - name: Documentation
    url: https://github.com/ThomasCardin/gobservability/blob/main/README.md
