---
apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook
  namespace: gobservability
type: Opaque
data:
  webhook_url: aHR0cHM6Ly9kaXNjb3JkLmNvbS9hcGkvd2ViaG9va3MvMTQxMDAwMzQ2MTI2MDU3NDgxMi85bUtiZC1hQXY3Vl9FNlNPaEdBUUVzLTI4SWVFOU9HR2gwNm1wd2tNX204R0k1Q3JyRURaT2s4V1BlNFhZQUczaGs2  # Discord webhook URL in base64