apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gobservability-postgres
  namespace: gobservability
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  instances: 1

  postgresql:
    parameters:
      timezone: "America/Montreal"
    shared_preload_libraries: []

  managed:
    roles:
      - name: gobs
        superuser: false
        login: true
        createdb: true

  bootstrap:
    initdb:
      database: gobservability
      owner: gobs
      secret:
        name: gobservability-postgres-user
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
        - SET timezone = 'America/Montreal';

  storage:
    size: 5Gi
    storageClass: hdd-ceph-block
