apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobservability-server
  namespace: {{ .Values.namespace }}
  labels:
    app: gobservability-server
spec:
  replicas: 1  # Fixed: server runs as single replica
  selector:
    matchLabels:
      app: gobservability-server
  template:
    metadata:
      labels:
        app: gobservability-server
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
      containers:
      - name: server
        image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
        imagePullPolicy: {{ .Values.server.image.pullPolicy }}
        args:
        - "./server"
        - "-port=8080"
        - "-grpc-port=9090"
        - "-mode={{ .Values.server.mode }}"
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: grpc
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.postgres.secretName }}
              key: {{ .Values.secrets.postgres.usernameKey }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.postgres.secretName }}
              key: {{ .Values.secrets.postgres.passwordKey }}
        - name: POSTGRES_URL
          value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@gobservability-postgres-rw.{{ .Values.namespace }}.svc.cluster.local:5432/gobservability?sslmode=disable"
        - name: DISCORD_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.discordWebhook.secretName }}
              key: {{ .Values.secrets.discordWebhook.key }}
        - name: GIN_MODE
          value: "{{ .Values.server.mode }}"
        resources:
          {{- toYaml .Values.server.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: gobservability-server
  namespace: {{ .Values.namespace }}
  labels:
    app: gobservability-server
  {{- if .Values.server.service.annotations }}
  annotations:
    {{- toYaml .Values.server.service.annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: gobservability-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  - protocol: TCP
    port: 9090
    targetPort: 9090
    name: grpc
  type: {{ .Values.server.service.type }}
