apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobservability-server
  namespace: gobservability
  labels:
    app: gobservability-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gobservability-server
  template:
    metadata:
      labels:
        app: gobservability-server
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: server
        image: ghcr.io/thomascardin/gobservability-server
        imagePullPolicy: Always
        args: ["./server", "-port=8080", "-grpc-port=9090", "-mode=release"]
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: grpc
        env:
        - name: POSTGRES_URL
          value: "postgres://gobs:gobs123@gobservability-postgres-rw.gobservability.svc.cluster.local:5432/gobservability?sslmode=disable"
        - name: DISCORD_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: discord-webhook
              key: webhook_url
        - name: GIN_MODE
          value: "release"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: gobservability-server
  namespace: gobservability
  labels:
    app: gobservability-server
spec:
  selector:
    app: gobservability-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  - protocol: TCP
    port: 9090
    targetPort: 9090
    name: grpc
  type: ClusterIP
